enabled = 1
type = "mysql"
dsn = "mysql:host=127.0.0.1;port=3306;dbname=app_db;charset=utf8mb4"
host = "127.0.0.1"
port = "3306"
dbname = "app_db"
user = "app_db"
password = "app_db"
options[MYSQL_ATTR_INIT_COMMAND] = "SET NAMES 'utf8mb4'"
defaultTableEngine = "InnoDB"
defaultCollate = "utf8mb4_unicode_ci"
prefix = "db_ir"
pageSize = 5

;PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
attrs[3] = 2
